print ("ch3¢k help")
print ("Version 1.00")
usrinput = str("What can we help you with? type \help for more help")
if usrinput = ("\help")
   print ("List of help commands")
   print ("---------------------")
   print ("\Compatibility       ")
   print ("---------------------")
   print ("\Clear screen ouput  ")
   print ("---------------------")
   print ("\About               ")
   print ("---------------------")
   print ("\Convert (US)        ")
   print ("---------------------")
   print ("\Convert (US)        ")
if usrinput = ("Compatibility")
   print ("ch3¢k Compatibility")
   print ("===================")
   print ("Windows            ")
   print ("===================")
   print ("Windows XP         ")
   print ("Windows Server 2003")
   print ("Windows Vista      ")
   print ("Windows Server 2008")
   print ("Windows 7          ")
   print ("Windows 8          ")
   print ("Windows Server 2012")
   print ("Windows 8.1        ")
   print ("Windows 10         ")
   print ("32 bit & 64 bit    ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("===================")
   print ("Mac/IOS            ")
   print ("===================")
   print ("Mac OS X 10.1      ")
   print ("Mac OS X 10.2      ")
   print ("Mac OS X 10.3      ")
   print ("Mac OS X 10.4      ")
   print ("Mac OS X 10.5      ")
   print ("Mac OS X 10.6      ")
   print ("Mac OS X 10.7      ")
   print ("Mac OS X 10.8      ")
   print ("Mac OS X 10.9      ")
   print ("Mac OS X 10.10     ")
   print ("Mac OS X 10.11     ")
   print ("Mac OS X 10.12     ")
   print ("Mac OS X 10.13     ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("IOS 6.0            ")
   print ("IOS 7.0            ")
   print ("IOS 8.0            ")
   print ("IOS 9.0            ")
   print ("IOS 10.0           ")
   print ("IOS 11.0           ")
   print ("IOS 12.0           ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("===================")
   print ("Unix/Linux         ")
   print ("===================")
   print ("Android 4.4        ")
   print ("Android 5.1        ")
   print ("Android 6.0        ")
   print ("Android 7.0        ")
   print ("Android 7.1        ")
   print ("Android 8.0        ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("Ubuntu 10.04       ")
   print ("Ubuntu 10.10       ")
   print ("Ubuntu 11.04       ")
   print ("Ubuntu 11.10       ")
   print ("Ubuntu 12.04       ")
   print ("Ubuntu 12.10       ")
   print ("Ubuntu 13.04       ")
   print ("Ubuntu 13.10       ")
   print ("Ubuntu 14.04       ")
   print ("Ubuntu 14.10       ")
   print ("Ubuntu 15.04       ")
   print ("Ubuntu 15.10       ")
   print ("Ubuntu 16.04       ")
   print ("Ubuntu 16.10       ")
   print ("Ubuntu 17.04       ")
   print ("Ubuntu 17.10       ")
   print ("Ubuntu 18.04       ")
   print ("Ubuntu 18.10       ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("Fedora 6           ")
   print ("Fedora 7           ")
   print ("Fedora 8           ")
   print ("Fedora 9           ")
   print ("Fedora 10          ")
   print ("Fedora 11          ")
   print ("Fedora 12          ")
   print ("Fedora 13          ")
   print ("Fedora 14          ")
   print ("Fedora 15          ")
   print ("Fedora 16          ")
   print ("Fedora 17          ")
   print ("Fedora 18          ")
   print ("Fedora 19          ")
   print ("Fedora 20          ")
   print ("Fedora 21          ")
   print ("Fedora 22          ")
   print ("Fedora 23          ")
   print ("Fedora 24          ")
   print ("Fedora 25          ")
   print ("Fedora 26          ")
   print ("Fedora 27          ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("Gentoo Linux 1.0   ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("===================")
   print ("NOT SUPPORTED      ")
   print ("===================")
   print ("Windows            ")
   print ("===================")
   print ("Windows ME         ")
   print ("Windows 2000       ")
   print ("Windows 98 SE      ")
   print ("Windows 98         ")
   print ("Windows 95         ")
   print ("Windows NT 4       ")
   print ("Windows 3.51       ")
   print ("Windows 3.5        ")
   print ("Windows 3.2        ")
   print ("Windows 3.11       ")
   print ("Windows 3.1        ")
   print ("Windows 3.0        ")
   print ("Windows 2.1        ")
   print ("Windows 2.04       ")
   print ("Windows 2.03       ")
   print ("Windows 2.02       ")
   print ("Windows 2.01       ")
   print ("Windows 2.0        ")
   print ("Windows 1.04       ")
   print ("Windows 1.03       ")
   print ("Windows 1.02       ")
   print ("Windows 1.01       ")
   print ("Windows 1.00       ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("===================")
   print ("Mac / IOS          ")
   print ("===================")
   print ("Classic MacOS 1    ")
   print ("Classic MacOS 2    ")
   print ("Classic MacOS 3    ")
   print ("Classic MacOS 4    ")
   print ("Classic MacOS 5    ") 
   print ("Classic MacOS 6    ")
   print ("Classic MacOS 7    ")
   print ("Classic MacOS 7.5  ")
   print ("Classic MacOS 8    ")
   print ("Classic MacOS 9    ")
   print ("Mac OS X 10.0      ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("IOS 5.0            ")
   print ("IOS 4.0            ")
   print ("IOS 3.0            ")
   print ("IOS 2.0            ")
   print ("IOS 1.0            ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")
   print ("===================")
   print ("Unix / Linux       ")
   print ("===================")
   print ("Android 4.1        ")
   print ("Android 3x         ")
   print ("Android 2x         ")
   print ("Android 1x         ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")    
   print ("Ubuntu 9.10        ")
   print ("Ubuntu 9.04        ")
   print ("Ubuntu 8.10        ")
   print ("Ubuntu 8.04        ")
   print ("Ubuntu 7.10        ") 
   print ("Ubuntu 7.04        ")
   print ("Ubuntu 6.10        ")
   print ("Ubuntu 6.04        ")
   print ("Ubuntu 5.10        ")
   print ("Ubuntu 5.04        ")
   print ("Ubuntu 4.10        ")
   print ("Ubuntu 4.04        ")
usrinput = str("Load more? Y/N")
if usrinput = ("Y")  
